question_data = [
    {"type": "multiple",
     "difficulty":"easy",
     "category": "Entertainment: Music",
     "question": "Which band recorded the album &quot;Parallel Lines&quot;?",
     "correct_answer": "Blondie",
     "incorrect_answers": ["Paramore", "Coldplay", "The Police"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Music",
     "question": "American rapper Dr. Dre actually has a Ph.D. doctorate.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "multiple", "difficulty": "hard", "category": "Entertainment: Music",
     "question": "What is the official name of Prince&#039;s backing band?",
     "correct_answer": "The Revolution",
     "incorrect_answers": ["The Paupers", "The Wailers", "The Heartbreakers"]},
    {"type": "multiple", "difficulty": "hard", "category": "Entertainment: Music",
     "question": "What was the last Aphex Twin album released before his decade-long hiatus?",
     "correct_answer": "Drukqs", "incorrect_answers": ["Windowlicker", "Syro", "Collected Ambient Works 85-92"]},
    {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Music",
     "question": "Madonna&#039;s song &quot;Hung Up&quot; includes a piece from which popular 70s song?",
     "correct_answer": "Gimmie! Gimmie! Gimme! (A Man After Midnight)",
     "incorrect_answers": ["Staying Alive", "Night Fever", "The Chain"]},
    {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Music",
     "question": "The band STRFKR was also briefly known as Pyramiddd.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "multiple", "difficulty": "hard", "category": "Entertainment: Music",
     "question": "Who was not in the band &quot;The Smiths&quot;?",
     "correct_answer": "Martin Chambers",
     "incorrect_answers": ["Morrissey", "Andy Rourke", "Mike Joyce"]},
    {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Music",
     "question": "Which popular rock band has a one-armed drummer?", "correct_answer": "Def Leppard",
     "incorrect_answers": ["The Beatles", "Lynyrd Skynyrd", "Foreigner"]},
    {"type": "multiple", "difficulty": "easy", "category": "Entertainment: Music",
     "question": "Brian May was the guitarist for which band?", "correct_answer": "Queen",
     "incorrect_answers": ["Pink Floyd", "Rolling Stones", "The Doors"]},
    {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Music",
     "question": "What is the real name of Canadian electronic music producer deadmau5?",
     "correct_answer": "Joel Zimmerman",
     "incorrect_answers": ["Sonny Moore", "Adam Richard Wiles", "Thomas Wesley Pentz"]},
    {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Music",
     "question": "Rick Astley&#039;s hit song &quot;Never Gonna Give You Up&quot; was released in what year?",
     "correct_answer": "1987", "incorrect_answers": ["1985", "1986", "1988"]},
    {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Music",
     "question": "Which country does the power metal band &quot;Sabaton&quot; originate from?",
     "correct_answer": "Sweden", "incorrect_answers": ["Germany", "United States", "Finland"]},
    {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Music",
     "question": "Which iconic album cover features the pulsar waves of CP 1919 placed in the center of the cover?",
     "correct_answer": "Unknown Pleasures",
     "incorrect_answers": ["The Dark Side of the Moon", "London Calling", "The Velvet Underground &amp; Nico"]},
    {"type": "multiple", "difficulty": "hard", "category": "Entertainment: Music",
     "question": "Which lyric is about Red Hot Chili Peppers frontman Anthony Kiedis?",
     "correct_answer": "&quot;A rainy Lithuanian \/ Is dancing as an Indian&quot;",
     "incorrect_answers": ["&quot;Fly away on, my zephyr \/ I feel it more than ever&quot;",
                           "&quot;And I liked the dimple in your chin \/ Your pale blue eyes&quot;",
                           "&quot;You used to be so warm and affectionate...but now you&#039;re quick to get into your regret&quot;"]},
    {"type": "multiple", "difficulty": "hard", "category": "Entertainment: Music",
     "question": "What is the name of the 2016 mixtape released by Venezuelan electronic producer Arca?",
     "correct_answer": "Entra&ntilde;as", "incorrect_answers": ["&amp;&amp;&amp;&amp;&amp;&amp;", "Sheep", "Xen"]},
    {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Music",
     "question": "Which European capital city gives its name to a 1981 song by Ultravox?", "correct_answer": "Vienna",
     "incorrect_answers": ["Berlin", "Paris", "Brussels"]},
    {"type": "multiple", "difficulty": "easy", "category": "Entertainment: Music",
     "question": "Which artist released the 2012 single &quot;Harlem Shake&quot;, which was used in numerous YouTube videos in 2013?",
     "correct_answer": "Baauer", "incorrect_answers": ["RL Grime", "NGHTMRE", "Flosstradamus"]},
    {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Music",
     "question": "Which of these artists was NOT a member of the electronic music supergroup Swedish House Mafia, which split up in 2013?",
     "correct_answer": "Alesso", "incorrect_answers": ["Steve Angello", "Sebastian Ingrosso", "Axwell"]},
    {"type": "multiple", "difficulty": "easy", "category": "Entertainment: Music",
     "question": "The Rush song &quot;YYZ&quot; derives its name from the IATA aiport identification code for which city?",
     "correct_answer": "Toronto", "incorrect_answers": ["Vancouver", "Ottawa", "Calgary"]},
    {"type": "multiple",
     "difficulty": "medium",
     "category": "Entertainment: Music",
     "question": "Which song in Drake&#039;s &quot;Views&quot; features Future?",
     "correct_answer": "Grammys",
     "incorrect_answers": ["Too Good", "Faithful", "Pop Style"]}]
